version: '2'

networks:
  default:

services:

  orderer.hf.baltransfer.io:
    image: hyperledger/fabric-orderer:x86_64-1.0.5
    container_name: orderer.hf.baltransfer.io
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISPROFILE=BalTransfer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=hf.baltransfer.io
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./artifacts/orderer.genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/hf.baltransfer.io/orderers/orderer.hf.baltransfer.io/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/hf.baltransfer.io/orderers/orderer.hf.baltransfer.io/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      default:
        aliases:
          - orderer.hf.baltransfer.io

  ca.org1.hf.baltransfer.io:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    container_name: ca.org1.hf.baltransfer.io
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.hf.baltransfer.io
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.baltransfer.io-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c5634eca32fcd8432fb434e76afe951751dce29cc6276004ed9fc3936e96b504_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.hf.baltransfer.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c5634eca32fcd8432fb434e76afe951751dce29cc6276004ed9fc3936e96b504_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.hf.baltransfer.io/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      default:
        aliases:
          - ca.org1.hf.baltransfer.io

  ca.org2.hf.baltransfer.io:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    container_name: ca.org2.hf.baltransfer.io
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.hf.baltransfer.io
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.hf.baltransfer.io-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1778eb3bedba3366638dcca36a167e964f61f958c28d5f7219f6f3ce50777fa8_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.hf.baltransfer.io-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1778eb3bedba3366638dcca36a167e964f61f958c28d5f7219f6f3ce50777fa8_sk
    ports:
      - 7058:7058
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.hf.baltransfer.io/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      default:
        aliases:
          - ca.org2.hf.baltransfer.io

  peer0.org1.hf.baltransfer.io:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer0.org1.hf.baltransfer.io
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=baltransfer
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.hf.baltransfer.io
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org1.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.baltransfer.io
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org1.hf.baltransfer.io
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.baltransfer.io/peers/peer0.org1.hf.baltransfer.io/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.baltransfer.io/peers/peer0.org1.hf.baltransfer.io/tls:/var/hyperledger/tls
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:7055
      - 7057:7057
    depends_on:
      - orderer.hf.baltransfer.io
    links:
      - orderer.hf.baltransfer.io
    networks:
      default:
        aliases:
          - peer0.org1.hf.baltransfer.io

  peer1.org1.hf.baltransfer.io:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer1.org1.hf.baltransfer.io
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=baltransfer
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer1.org1.hf.baltransfer.io
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org1.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org1.hf.baltransfer.io
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.org1.hf.baltransfer.io
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.hf.baltransfer.io/peers/peer1.org1.hf.baltransfer.io/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org1.hf.baltransfer.io/peers/peer1.org1.hf.baltransfer.io/tls:/var/hyperledger/tls
    ports:
      - 8051:7051
      - 8053:7053
      - 8055:7055
      - 8057:7057
    depends_on:
      - orderer.hf.baltransfer.io
    links:
      - orderer.hf.baltransfer.io
    networks:
      default:
        aliases:
          - peer1.org1.hf.baltransfer.io

  peer0.org2.hf.baltransfer.io:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer0.org2.hf.baltransfer.io
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=baltransfer
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer0.org2.hf.baltransfer.io
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.org2.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org2.hf.baltransfer.io
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.org2.hf.baltransfer.io
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.hf.baltransfer.io/peers/peer0.org2.hf.baltransfer.io/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org2.hf.baltransfer.io/peers/peer0.org2.hf.baltransfer.io/tls:/var/hyperledger/tls
    ports:
      - 7155:7055
      - 7157:7057
      - 7153:7053
      - 7151:7051
    depends_on:
      - orderer.hf.baltransfer.io
    links:
      - orderer.hf.baltransfer.io
    networks:
      default:
        aliases:
          - peer0.org2.hf.baltransfer.io

  peer1.org2.hf.baltransfer.io:
    image: hyperledger/fabric-peer:x86_64-1.0.5
    container_name: peer1.org2.hf.baltransfer.io
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=baltransfer
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer1.org2.hf.baltransfer.io
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.org2.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.hf.baltransfer.io:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=org2.hf.baltransfer.io
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.org2.hf.baltransfer.io
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.hf.baltransfer.io/peers/peer1.org2.hf.baltransfer.io/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/org2.hf.baltransfer.io/peers/peer1.org2.hf.baltransfer.io/tls:/var/hyperledger/tls
    ports:
      - 8155:7055
      - 8157:7057
      - 8153:7053
      - 8151:7051
    depends_on:
      - orderer.hf.baltransfer.io
    links:
      - orderer.hf.baltransfer.io
    networks:
      default:
        aliases:
          - peer1.org2.hf.baltransfer.io
